#FROM python:3.10-slim
FROM python:3.11-slim


# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
	redis-tools \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y docker.io

	

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

#RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the application code
COPY . .

# Copy the start script and ensure it is executable
COPY ./docker/worker_entrypoint /worker_entrypoint
RUN chmod +x /worker_entrypoint


# Define the default command
ENTRYPOINT ["/worker_entrypoint"]
