services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_celery_example_web
    command: /start
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data:/data  
    ports:
      - 8010:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_celery_example_celery_worker
    command: /worker_entrypoint
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data:/data
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

volumes:
  postgres_data: