#!/bin/sh

#until cd /app
#do
#    echo "Waiting for server volume..."
#done


until python3 manage.py makemigrations
do
    echo "Waiting for db to be ready..."
    sleep 2
done

until python3 manage.py makemigrations shared
do
    echo "Waiting for db to be ready..."
    sleep 2
done

until python3 manage.py makemigrations api
do
    echo "Waiting for db to be ready..."
    sleep 2
done


until python3 manage.py makemigrations user
do
    echo "Waiting for db to be ready..."
    sleep 2
done

until python3 manage.py migrate
do
    echo "Waiting for db to be ready..."
    sleep 2
done

until python3 manage.py collectstatic --noinput
do
    echo "Waiting for collecstatic to be ready..."
    sleep 2
done

mkdir -p ../data/tests
until rsync ./static/tests ../data/tests
do
    echo "Waiting moving tests"
    sleep 2
done
rm ../data/static/tests

until python3 manage.py loaddata static/initial_data.json
do
    echo "Waiting for loading initial data"
    sleep 2
done

# python manage.py createsuperuser --noinput

#gunicorn pandora.wsgi --bind 0.0.0.0:8000 --workers 4 --threads 4

# for debug
python3 manage.py runserver 0.0.0.0:8000