"""
Django settings for pandora project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

import os
import sys
#try:
#    from .local_settings import *
#except ImportError:
#    pass


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


sys.modules['fontawesome_free'] = __import__('fontawesome-free')

# Application definition
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'crispy_forms',
	'crispy_bootstrap5',
	'corsheaders',
	'rest_framework',
	'rest_framework.authtoken',
	'rest_framework_simplejwt',
	'administration',
	'shared',
	'social_django',
	'fontawesome_free',
	# Celery apps
	'celery',
	'celery_progress',
	'api',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Celery Progress Settings
CELERY_PROGRESS_BACKEND = 'celery_progress.backends.redis.RedisBackend'
CELERY_PROGRESS_EXPIRES = 60 * 60  # 1 hour

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pandora.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'administration', 'templates'), os.path.join(BASE_DIR, 'user', 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'social_django.context_processors.backends',
				'social_django.context_processors.login_redirect',
			],
		},
	},
]

WSGI_APPLICATION = 'pandora.wsgi.application'

AUTHENTICATION_BACKENDS = (
	'social_core.backends.github.GithubOAuth2',
	'django.contrib.auth.backends.ModelBackend',
)

LOGOUT_REDIRECT_URL = '/'
SOCIAL_AUTH_URL_NAMESPACE = 'social'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'user_dashboard'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
#USE_TZ = True


USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = '/static/'

LOCAL_STATIC_CDN_PATH = os.path.join(os.path.dirname(BASE_DIR), 'data')
DOCKER_CDN_PATH = '/home/franciscochambel/data'

SUBMISSIONS_ROOT = 'submissions/'
TESTS_ROOT = 'tests/'
CONTESTS_ROOT = 'contests/'
DATAFILES_ROOT = 'datafiles/'




STATIC_ROOT = os.path.join(LOCAL_STATIC_CDN_PATH, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(LOCAL_STATIC_CDN_PATH)
MEDIA_URL = '/media/' # django-storages
URL_PREFIX = 'pandora/'

SOCIAL_AUTH_REVOKE_TOKENS_ON_DISCONNECT = True

# static analyzer configuration
STATIC_ANALYZER = 'cppcheck --enable=all .'

# valgrind configuration
VALGRIND_EXEC = '/usr/bin/valgrind --error-exitcode=77 --leak-check=full -q'

# Celery Settings
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'

BROKER_URL = 'redis://redis:6379/0'  # Redis container service name
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'


# Celery Configuration Options
CELERY_TIMEZONE = "Europe/Lisbon"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60



# LOGGING = {
# 	'version': 1,
# 	'disable_existing_loggers': False,
# 	'handlers': {
# 		'console': {
# 			'class': 'logging.StreamHandler',
# 		},
# 	},
# 	'root': {
# 		'handlers': ['console'],
# 		'level': 'DEBUG',
# 	},  
# }


LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'handlers': {
		'console': {
			'class': 'logging.StreamHandler',
		},
	},
	'root': {
		'handlers': ['console'],
		'level': 'DEBUG',
	},
	'loggers': {
		'celery': {
			'handlers': ['console'],
			'level': 'DEBUG',
			'propagate': False,
		},
	},
}

REST_FRAMEWORK = {
	"DEFAULT_AUTHENTICATION_CLASSES": [
		"rest_framework.authentication.SessionAuthentication",
		 "api.authentication.TokenAuthentication",
		 "rest_framework_simplejwt.authentication.JWTAuthentication",
	],
	"DEFAULT_PERMISSION_CLASSES": [
		"rest_framework.permissions.IsAuthenticatedOrReadOnly"
	],
	"DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
	"PAGE_SIZE": 100
}

#BASE_USR_PATH = 'pandora/'
BASE_USR_PATH = ''


ENABLE_USER_REGISTRATION = True


# try:
#     from .local_settings import *
# except ImportError:
#     pass


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3')
#     }
# }



SECRET_KEY = os.environ.get(
	"SECRET_KEY", "django-insecure-6hdy-)5o6k6it_6x%s#u0#guc3(au!=v%%qb674(upu6rrht7b"
)

DEBUG = os.environ.get("DEBUG", True)

ALLOWED_HOSTS = ["127.0.0.1", "0.0.0.0", "localhost"]

if os.environ.get("ALLOWED_HOSTS") is not None:
	try:
		ALLOWED_HOSTS += os.environ.get("ALLOWED_HOSTS").split(",")
	except Exception as e:
		print("Cant set ALLOWED_HOSTS, using default instead")


DATABASES = {
	"default": {
		"ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
		"NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
		"USER": os.environ.get("SQL_USER", "user"),
		"PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
		"HOST": os.environ.get("SQL_HOST", "localhost"),
		"PORT": os.environ.get("SQL_PORT", "5432"),
	}
}

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BACKEND", "redis://127.0.0.1:6379/0")

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BACKEND", "redis://redis:6379/0")

CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"

DATABASES = {
	"default": {
		"ENGINE": "django.db.backends.postgresql",
		"NAME": os.environ.get("POSTGRES_DB", "hello_django"),
		"USER": os.environ.get("POSTGRES_USER", "hello_django"),
		"PASSWORD": os.environ.get("POSTGRES_PASSWORD", "hello_django"),
		"HOST": os.environ.get("POSTGRES_HOST", "db"),
		"PORT": os.environ.get("POSTGRES_PORT", "5432"),
	}
}


#
# rest of the code ...
#

# set database, it can be set to SQLite or Postgres

#DB_SQLITE = "sqlite"
#DB_POSTGRESQL = "postgresql"

# DATABASES_ALL = {
#     DB_SQLITE: {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     },
#     DB_POSTGRESQL: {
#         "ENGINE": "django.db.backends.postgresql",
#         "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
#         "NAME": os.environ.get("POSTGRES_NAME", "postgres"),
#         "USER": os.environ.get("POSTGRES_USER", "postgres"),
#         "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
#         "PORT": int(os.environ.get("POSTGRES_PORT", "5432")),
#     },
# }

#DATABASES = {"default": DATABASES_ALL[os.environ.get("DJANGO_DB", DB_SQLITE)]}

